import React, { useEffect, useState } from "react";
import { BrowserRouter as Router, Routes, Route, Navigate, useNavigate, useLocation } from "react-router-dom";

// Import your page components
import Landing from "./pages/Landing";
import Login from "./pages/Login.jsx";
import Dashboard from "./pages/Dashboard"; 

/**
 * Legal & Support Components
 */
const LegalLayout = ({ title, children }) => (
  <div className="flex-1 flex flex-col items-center py-20 px-6 text-white bg-[#0a0118] min-h-screen">
    <div className="max-w-3xl w-full">
      <h1 className="text-5xl font-extrabold mb-10 bg-gradient-to-r from-white to-purple-500 bg-clip-text text-transparent">
        {title}
      </h1>
      <div className="space-y-6 text-gray-400 leading-relaxed text-lg">
        {children}
      </div>
      <button 
        onClick={() => window.history.back()} 
        className="mt-12 text-purple-400 hover:text-purple-300 transition-colors font-bold uppercase tracking-widest text-sm"
      >
        ← Return to MetriaAI
      </button>
    </div>
  </div>
);

const Privacy = () => (
  <LegalLayout title="Privacy Policy">
    <p>Last Updated: December 2025</p>
    <h2 className="text-white text-2xl font-bold mt-8">1. Data Collection</h2>
    <p>MetriaAI accesses your Google profile and email via OAuth to provide personalized analytics. We do not store or share your private data with third parties.</p>
    <div className="p-6 border-l-4 border-purple-500 bg-[#160b2e] text-white my-8">
      <strong>Google Limited Use Disclosure:</strong><br/>
      MetriaAI’s use and transfer of information received from Google APIs to any other app will adhere to the <a href="https://developers.google.com/identity/protocols/oauth2/policies#user-data-policy" className="underline text-purple-400">Google API Services User Data Policy</a>, including the Limited Use requirements.
    </div>
    <h2 className="text-white text-2xl font-bold mt-8">2. Data Usage</h2>
    <p>We use session-based data to generate executive-ready intelligence. You may request data deletion at any time by contacting support.</p>
  </LegalLayout>
);

const Terms = () => (
  <LegalLayout title="Terms of Service">
    <p>By using MetriaAI, you agree to these conditions:</p>
    <h2 className="text-white text-2xl font-bold mt-8">1. Service Nature</h2>
    <p>MetriaAI provides autonomous AI synthesis. While we strive for tactical precision, insights are generated by AI and should be verified for mission-critical decisions.</p>
    <h2 className="text-white text-2xl font-bold mt-8">2. Intellectual Property</h2>
    <p>The "Neural Engine" and its associated logic are the property of MetriaAI. Unauthorized reverse engineering is strictly prohibited.</p>
  </LegalLayout>
);

const Contact = () => (
  <LegalLayout title="Contact Support">
    <p>Need assistance with the Metria Neural Engine? Our team is available for technical support, integration help, and enterprise inquiries.</p>
    <div className="mt-10 p-8 rounded-2xl bg-[#13111c] border border-white/5">
      <h3 className="text-white font-bold mb-2 uppercase tracking-widest text-xs opacity-50">Email Support</h3>
      <p className="text-purple-400 font-mono text-xl mb-6 select-all">mandlandhlovu264@gmail.com</p>
      <h3 className="text-white font-bold mb-2 uppercase tracking-widest text-xs opacity-50">Response Time</h3>
      <p className="text-gray-400">Our typical response window is 24-48 business hours.</p>
    </div>
    <div className="mt-10">
      <h3 className="text-white font-bold mb-4 italic">Verification Transparency</h3>
      <p className="text-sm text-gray-500">
        MetriaAI is operated by Metria Neural Systems. For data privacy inquiries or to exercise your right to data deletion, please contact our support desk above.
      </p>
    </div>
  </LegalLayout>
);

/**
 * AppWrapper component manages global auth and payment synchronization.
 */
function AppWrapper() {
  const navigate = useNavigate();
  const location = useLocation();
  const [profile, setProfile] = useState(null); 
  const [isHydrated, setIsHydrated] = useState(false); 
  const [showToast, setShowToast] = useState(false);

  // Unified function to check backend for current user status
  const checkAuth = async () => {
    const token = localStorage.getItem("adt_token");
    if (!token) {
      setProfile(null);
      return null;
    }

    try {
      // CACHE-BUSTER: Ensures Render and Browser serve fresh DB data.
      const response = await fetch(`https://ai-data-analyst-backend-1nuw.onrender.com/api/auth/me?v=${Date.now()}`, {
        headers: { 
          "Authorization": `Bearer ${token}`,
          "Cache-Control": "no-cache",
          "Pragma": "no-cache"
        }
      });
      
      if (response.ok) {
        const userData = await response.json();
        
        /**
         * MISMATCH FIX:
         * Backend sends 'id', but some components might expect 'user_id'.
         * We map both to ensure absolute compatibility.
         */
        const activeProfile = { 
          ...userData, 
          user_id: userData.id, 
          token 
        };

        localStorage.setItem("adt_profile", JSON.stringify(activeProfile));
        setProfile(activeProfile);
        return activeProfile;
      } else {
        localStorage.clear();
        setProfile(null);
        return null;
      }
    } catch (err) {
      console.error("Auth Sync Failed:", err);
      const saved = localStorage.getItem("adt_profile");
      if (saved) {
        const p = { ...JSON.parse(saved), token };
        setProfile(p);
        return p;
      }
      return null;
    }
  };

  useEffect(() => {
    const initApp = async () => {
      // 1. Check if we are returning from a successful payment
      if (location.search.includes("payment=success")) {
        console.log("💳 Payment detected. Initiating ID-First Neural Sync...");
        let attempts = 0;
        const maxAttempts = 15; 

        while (attempts < maxAttempts) {
          console.log(`Neural Sync Attempt ${attempts + 1}/${maxAttempts}...`);
          const currentProfile = await checkAuth();
          
          /**
           * ARCHITECTURAL TELEPORT: 
           * Using subscription_id as the Master Key.
           */
          if (currentProfile?.subscription_id || currentProfile?.is_active) {
            console.log("🚀 Subscription verified! Teleporting to Dashboard.");
            setShowToast(true);
            setTimeout(() => setShowToast(false), 5000);
            
            // Redirect immediately
            navigate("/dashboard/overview", { replace: true });
            setIsHydrated(true);
            return; 
          }
          
          attempts++;
          if (attempts < maxAttempts) {
            await new Promise(res => setTimeout(res, 4000)); 
          }
        }
        
        // Final fallback
        const finalCheck = await checkAuth();
        if (finalCheck?.is_active) {
            navigate("/dashboard/overview", { replace: true });
        } else {
            navigate("/", { replace: true });
        }
      } else {
        await checkAuth();
      }
      
      setIsHydrated(true);
    };
    
    initApp();
  }, [location.search]);

  const handleLoginSuccess = async (userId, token) => { 
    localStorage.setItem("adt_token", token);
    const success = await checkAuth();
    if (success) navigate(`/dashboard/overview`);
  };

  const handleLogout = () => {
    localStorage.clear();
    setProfile(null);
    navigate("/");
  };

  // HYDRATION GUARD: Prevents flashes of Landing page during Sync
  if (!isHydrated) return (
    <div className="min-h-screen bg-[#0a0118] flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
            <div className="w-10 h-10 border-4 border-purple-500/10 border-t-purple-500 rounded-full animate-spin"></div>
            <p className="text-purple-500/40 text-[10px] uppercase tracking-[0.4em] font-bold animate-pulse">
                {location.search.includes("payment=success") ? "Verifying Subscription" : "Synchronizing Neural Core"}
            </p>
        </div>
    </div>
  );

  return (
    <>
      {showToast && (
        <div className="fixed top-10 left-1/2 -translate-x-1/2 z-[9999] animate-bounce">
          <div className="bg-purple-600 text-white px-6 py-3 rounded-full border border-white/20 shadow-2xl flex items-center gap-3">
            <span className="text-xl">🚀</span>
            <span className="font-bold tracking-tight text-sm uppercase">Neural Core Upgraded: Subscription Active</span>
          </div>
        </div>
      )}

      <Routes>
        <Route path="/" element={profile ? <Navigate to="/dashboard/overview" replace /> : <Landing onGetStarted={() => navigate("/login")} />} />
        
        <Route path="/login" element={profile ? <Navigate to="/dashboard/overview" replace /> : <Login onLoginSuccess={handleLoginSuccess} />} />

        <Route path="/dashboard/*" element={profile ? (
            <Dashboard profile={profile} onLogout={handleLogout} refetchProfile={checkAuth} /> 
          ) : (
            <Navigate to="/" replace />
          )}
        >
          <Route path="overview" element={<Dashboard.Overview profile={profile} />} />
          <Route path="analytics" element={<Dashboard.Analytics profile={profile} onLogout={handleLogout} />} />
          <Route 
            path="integrations" 
            element={<Dashboard.Integrations profile={profile} onLogout={handleLogout} refetchProfile={checkAuth} />} 
          /> 
          <Route path="profile" element={<Dashboard.Profile profile={profile} />} />
          <Route path="trends" element={<Dashboard.Trends profile={profile} />} />
          <Route index element={<Navigate replace to="overview" />} />
        </Route>

        <Route path="/privacy" element={<Privacy />} />
        <Route path="/terms" element={<Terms />} />
        <Route path="/contact" element={<Contact />} />
        <Route path="*" element={<Navigate to={profile ? "/dashboard/overview" : "/"} replace />} />
      </Routes>
    </>
  );
}

export default function App() {
  return (
    <div className="min-h-screen w-full bg-[#0a0118] m-0 p-0 flex flex-col relative z-0"> 
      <Router>
        <AppWrapper />
      </Router>
    </div>
  );
}