import React, { useEffect, useState } from "react";
import { BrowserRouter as Router, Routes, Route, Navigate, useNavigate, useLocation } from "react-router-dom";

// Import your page components
import Landing from "./pages/Landing";
import Login from "./pages/Login.jsx";
import Dashboard from "./pages/Dashboard"; 
import GoogleSheetsAnalysis from "./pages/GoogleSheetsAnalysis";

/**
 * Legal & Support Components
 */
const LegalLayout = ({ title, children }) => (
  <div className="flex-1 flex flex-col items-center py-20 px-6 text-white bg-[#0a0118] min-h-screen">
    <div className="max-w-3xl w-full">
      <h1 className="text-5xl font-extrabold mb-10 bg-gradient-to-r from-white to-purple-500 bg-clip-text text-transparent">
        {title}
      </h1>
      <div className="space-y-6 text-gray-400 leading-relaxed text-lg">
        {children}
      </div>
      <button 
        onClick={() => window.history.back()} 
        className="mt-12 text-purple-400 hover:text-purple-300 transition-colors font-bold uppercase tracking-widest text-sm"
      >
        ← Return to MetriaAI
      </button>
    </div>
  </div>
);

const Privacy = () => (
  <LegalLayout title="Privacy Policy">
    <p>Last Updated: December 2025</p>
    <h2 className="text-white text-2xl font-bold mt-8">1. Data Collection</h2>
    <p>MetriaAI accesses your Google profile and email via OAuth to provide personalized analytics. We do not store or share your private data with third parties.</p>
    <div className="p-6 border-l-4 border-purple-500 bg-[#160b2e] text-white my-8">
      <strong>Google Limited Use Disclosure:</strong><br/>
      MetriaAI’s use and transfer of information received from Google APIs to any other app will adhere to the <a href="https://developers.google.com/identity/protocols/oauth2/policies#user-data-policy" className="underline text-purple-400">Google API Services User Data Policy</a>, including the Limited Use requirements.
    </div>
    <h2 className="text-white text-2xl font-bold mt-8">2. Data Usage</h2>
    <p>We use session-based data to generate executive-ready intelligence. You may request data deletion at any time by contacting support.</p>
  </LegalLayout>
);

const Terms = () => (
  <LegalLayout title="Terms of Service">
    <p>By using MetriaAI, you agree to these conditions:</p>
    <h2 className="text-white text-2xl font-bold mt-8">1. Service Nature</h2>
    <p>MetriaAI provides autonomous AI synthesis. While we strive for tactical precision, insights are generated by AI and should be verified for mission-critical decisions.</p>
    <h2 className="text-white text-2xl font-bold mt-8">2. Intellectual Property</h2>
    <p>The "Neural Engine" and its associated logic are the property of MetriaAI. Unauthorized reverse engineering is strictly prohibited.</p>
  </LegalLayout>
);

const Contact = () => (
  <LegalLayout title="Contact Support">
    <p>Need assistance with the Metria Neural Engine? Our team is available for technical support, integration help, and enterprise inquiries.</p>
    <div className="mt-10 p-8 rounded-2xl bg-[#13111c] border border-white/5">
      <h3 className="text-white font-bold mb-2 uppercase tracking-widest text-xs opacity-50">Email Support</h3>
      <p className="text-purple-400 font-mono text-xl mb-6 select-all">mandlandhlovu264@gmail.com</p>
      <h3 className="text-white font-bold mb-2 uppercase tracking-widest text-xs opacity-50">Response Time</h3>
      <p className="text-gray-400">Our typical response window is 24-48 business hours.</p>
    </div>
    <div className="mt-10">
      <h3 className="text-white font-bold mb-4 italic">Verification Transparency</h3>
      <p className="text-sm text-gray-500">
        MetriaAI is operated by Metria Neural Systems. For data privacy inquiries or to exercise your right to data deletion, please contact our support desk above.
      </p>
    </div>
  </LegalLayout>
);

/**
 * AppWrapper component manages the global authentication state.
 */
function AppWrapper() {
  const navigate = useNavigate();
  const location = useLocation();
  const [profile, setProfile] = useState(null); 
  const [loading, setLoading] = useState(true);
  const [showToast, setShowToast] = useState(false);

  const refetchProfile = () => {
    const savedProfile = localStorage.getItem("adt_profile");
    const savedToken = localStorage.getItem("adt_token"); 

    if (savedProfile && savedToken) {
      try {
        const userProfile = JSON.parse(savedProfile);
        setProfile({ ...userProfile, token: savedToken });
        return true;
      } catch (e) {
        console.error("Error parsing profile from localStorage:", e);
        return false;
      }
    }
    setProfile(null);
    return false;
  };

  const checkSubscriptionStatus = async () => {
    const savedToken = localStorage.getItem("adt_token");
    if (!savedToken) return;

    try {
      const response = await fetch("https://ai-data-analyst-backend-1nuw.onrender.com/api/auth/me", {
        headers: { "Authorization": `Bearer ${savedToken}` }
      });
      
      if (response.ok) {
        const updatedUser = await response.json();
        localStorage.setItem("adt_profile", JSON.stringify(updatedUser));
        setProfile({ ...updatedUser, token: savedToken });
        
        // Show success toast if they are now active
        if (updatedUser.is_active) {
          setShowToast(true);
          setTimeout(() => setShowToast(false), 5000);
        }
      }
    } catch (err) {
      console.error("Failed to sync profile:", err);
    }
  };

  const handleLoginSuccess = (userId, token) => { 
    const savedProfile = JSON.parse(localStorage.getItem("adt_profile"));
    const newProfile = { user_id: userId, email: savedProfile?.email || "User", token: token }; 
    setProfile(newProfile);
    navigate(`/dashboard/overview`);
  };

  useEffect(() => {
    const initApp = async () => {
      // 1. Check for payment success flag in URL
      if (location.search.includes("payment=success")) {
        await checkSubscriptionStatus();
        // 2. Clean URL so toast doesn't re-trigger on refresh
        navigate(location.pathname, { replace: true });
      }
      refetchProfile(); 
      setLoading(false);
    };
    initApp();
  }, [location.pathname, location.search, navigate]);

  const handleLogout = () => {
    localStorage.removeItem("adt_profile");
    localStorage.removeItem("adt_token"); 
    setProfile(null);
    navigate("/");
  };

  if (loading) return null;

  return (
    <>
      {/* SUCCESS NOTIFICATION TOAST */}
      {showToast && (
        <div className="fixed top-10 left-1/2 -translate-x-1/2 z-[9999] animate-bounce">
          <div className="bg-purple-600 text-white px-6 py-3 rounded-full border border-white/20 shadow-2xl flex items-center gap-3">
            <span className="text-xl">🚀</span>
            <span className="font-bold tracking-tight">Neural Core Upgraded: Subscription Active</span>
          </div>
        </div>
      )}

      <Routes>
        <Route
          path="/"
          element={profile ? <Navigate to="/dashboard/overview" /> : <Landing onGetStarted={() => navigate("/login")} />}
        />

        <Route
          path="/login"
          element={profile ? <Navigate to="/dashboard/overview" /> : <Login onLoginSuccess={handleLoginSuccess} />}
        />

        <Route
          path="/dashboard/*"
          element={profile ? (
            <Dashboard profile={profile} onLogout={handleLogout} refetchProfile={refetchProfile} /> 
          ) : (
            <Navigate to="/" />
          )}
        >
          <Route path="overview" element={<Dashboard.Overview profile={profile} />} />
          <Route path="analytics" element={<Dashboard.Analytics profile={profile} onLogout={handleLogout} />} />
          <Route 
            path="integrations" 
            element={<Dashboard.Integrations profile={profile} onLogout={handleLogout} refetchProfile={refetchProfile} />} 
          /> 
          <Route path="profile" element={<Dashboard.Profile profile={profile} />} />
          <Route path="trends" element={<Dashboard.Trends profile={profile} />} />
          <Route index element={<Navigate replace to="overview" />} />
        </Route>

        <Route
          path="/google-sheets-analysis"
          element={profile ? <GoogleSheetsAnalysis profile={profile} /> : <Navigate to="/" />}
        />

        <Route path="/privacy" element={<Privacy />} />
        <Route path="/terms" element={<Terms />} />
        <Route path="/contact" element={<Contact />} />
        <Route path="*" element={<Navigate to="/" />} />
      </Routes>
    </>
  );
}

export default function App() {
  return (
    <div className="min-h-screen w-full bg-[#0a0118] m-0 p-0 flex flex-col relative z-0"> 
      <Router>
        <AppWrapper />
      </Router>
    </div>
  );
}